# Generated by Django 5.0.4 on 2024-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_by_alter_room_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'HOD')], default=1),
            preserve_default=False,
        ),
    ]
