# Generated by Django 5.0.4 on 2024-04-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_rename_questoin_id_comment_question_and_more'),
        ('user', '0004_subject_alter_hod_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.subject'),
            preserve_default=False,
        ),
    ]
