# Generated by Django 5.0.4 on 2024-04-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_rename_user_id_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='questoin_id',
            new_name='questoin',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
