# Generated by Django 5.0.4 on 2024-04-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_rename_questoin_id_comment_questoin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='questoin',
            new_name='question',
        ),
    ]
