# Generated by Django 5.0.4 on 2024-04-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_hod_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='hod',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='user_id',
        ),
    ]
