# Generated by Django 5.0.4 on 2024-04-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('user', '0005_rename_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
