# Generated by Django 5.0.4 on 2024-05-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_account_user_type_parent_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_number',
        ),
    ]
