# Generated by Django 5.0 on 2024-05-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('user', '0011_alter_student_parent_delete_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assignment.assignment'),
        ),
    ]
