# Generated by Django 5.0.4 on 2024-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_mainattendance_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainattendance',
            name='date_of_producing',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='mainattendance',
            unique_together={('attendance_type', 'date_of_producing')},
        ),
    ]
