# Generated by Django 5.0.4 on 2024-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_mainattendance_date_of_producing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date_of_marking',
            field=models.DateField(auto_now=True),
        ),
    ]
