# Generated by Django 5.0.4 on 2024-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_studentattendance_date_of_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodattendance',
            name='date_of_marking',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date_of_marking',
            field=models.DateField(auto_now=True),
        ),
    ]
