# Generated by Django 5.0.4 on 2024-04-22 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_hodattendance_table_alter_mainattendance_table_and_more'),
        ('classroom', '0002_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainattendance',
            name='classroom',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
